parameters:
     social_sandbox_user_provider.class: SocialSandbox\UserBundle\Security\Provider\SocialUserProvider

services:
     social_sandbox.user_provider:
         class: %social_sandbox_user_provider.class%
         arguments: [@fos_user.user_manager, { facebook: facebook_id } ] #options array e.g {facebook: facebook_id, google: google_id}
